version: '3'
services:
  node:
    build:
      context: .
    volumes:
      - ./:/next
    command: sh -c "yarn install && yarn run dev"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
