// import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from "react"
// import axios from 'axios'


const Page = () => {
  const [users, setUsers] = useState([]);
  // useEffect(() => {
  //   axios.get('https://jsonplaceholder.typicode.com/users')
  //     .then((res) => setUsers(res.data))
  //     .catch((error) => console.log(error))
  // }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App!あああ
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>いアイウ</p>
      <ul>
        {users.map((user) => (
          <li key={user.id}>
            {user.name}
          </li>
        ))}
      </ul>
    </div>
  )
}

export default Page;
